# Regularization parameters
defaults:
  - base

# Grid search
# >> see `scoring` of sklearn `GridSearchCV`
tuning:
  _target_: sklearn.model_selection.GridSearchCV
  param_grid:
    penalty: 
      - "l2"
    # >> see documentation for numpy's logspace
    C: 
      _target_: numpy.logspace
      start: -1
      stop: 1
      num: 100
  scoring: "f1_macro"
  cv: 10
  verbose: false
