# @package _global_

# hydra hijacks working directory by changing it to the current log directory,
work_dir: ${hydra:runtime.cwd}
# path to folder with data
data_dir: ${work_dir}/data 
seed: 42

data:
  labels: ${data_dir}/labels.csv
  summaries: ${data_dir}/summaries

defaults:
  - model: lr
  - hparams: lr
  - experiment: null
